import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/app/_context/CookieContext";
import {AlertProvider} from "@/app/_context/AlertContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// TODO 1: AuthProvider를 import 하세요
// import { ??? } from './_context/CookieContext';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* TODO 2: AuthProvider로 children을 감싸세요 */}
         <AuthProvider>
           <AlertProvider>
             {children}
           </AlertProvider>
         </AuthProvider>
      </body>
    </html>
  );
}
