services:
  mysql:
    image: mysql:8
    container_name: seung-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: urlshortener
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    container_name: seung-redis
    ports:
      - "6379:6379"